### ISSUE TITLE
没有range的玩意

### ISSUE THREAD

**Issue by geGDVS** [Kroos372/awaBot#3]
```python
Traceback (most recent call last):
  File "/home/container/mainBoter.py", line 898, in run
    msgGot(self, result["text"], rnick, result.get("trip"), "chat", customId=result.get("customId"), userid=result["userid"])
  File "/home/container/mainBoter.py", line 703, in msgGot
    context = func(chat, msg, sender, trip, type_, **kargs)
  File "/home/container/mainBoter.py", line 533, in mainfunc
    key = getStr()
  File "/home/container/const.py", line 506, in getStr
    for i in length:
TypeError: 'int' object is not iterable
```

**Comment by Kroos372** [comment]
/**
 *                    _ooOoo_
 *                   o8888888o
 *                   88" . "88
 *                   (| -_- |)
 *                    O\ = /O
 *                ____/`---'\____
 *              .   ' \\| |// `.
 *               / \\||| : |||// \
 *             / _||||| -:- |||||- \
 *               | | \\\ - /// | |
 *             | \_| ''\---/'' | |
 *              \ .-\__ `-` ___/-. /
 *           ___`. .' /--.--\ `. . __
 *        ."" '< `.___\_<|>_/___.' >'"".
 *       | | : `- \`.;`\ _ /`;.`/ - ` : | |
 *         \ \ `-. \_ __\ /__ _/ .-` / /
 * ======`-.____`-.___\_____/___.-`____.-'======
 *                    `=---='
 *
 * .............................................
 *          佛祖保佑             永无BUG
 */
